<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
    <PackageVersion Include="Novolis.Analyzers.StackBoundaries" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Cad.Primitives" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Math.Measure" Version="2026.1.*" />
  </ItemGroup>
</Project>

